//! ICMP forwarding errors generated by the local CONNECT-IP endpoint.

use bytes::Bytes;

use crate::h2::{TransportError, validate_ip_packet};

const IPV4_HEADER_LEN: usize = 20;
const IPV6_HEADER_LEN: usize = 40;
const ICMP_ERROR_HEADER_LEN: usize = 8;
const IPV6_MINIMUM_MTU: usize = 1_280;

pub(crate) fn packet_too_big(
    original: &[u8],
    maximum_packet_size: usize,
) -> Result<Bytes, TransportError> {
    validate_ip_packet(original)?;
    match original[0] >> 4 {
        4 => ipv4_packet_too_big(original, maximum_packet_size),
        6 => ipv6_packet_too_big(original, maximum_packet_size),
        _ => Err(TransportError::MalformedIpPacket),
    }
}

fn ipv4_packet_too_big(
    original: &[u8],
    maximum_packet_size: usize,
) -> Result<Bytes, TransportError> {
    let original_header_len = usize::from(original[0] & 0x0f) * 4;
    let quote_len = original.len().min(original_header_len.saturating_add(8));
    let total_len = IPV4_HEADER_LEN + ICMP_ERROR_HEADER_LEN + quote_len;
    let mut packet = vec![0_u8; total_len];

    packet[0] = 0x45;
    packet[2..4].copy_from_slice(&(total_len as u16).to_be_bytes());
    packet[8] = 64;
    packet[9] = 1;
    packet[12..16].copy_from_slice(&original[16..20]);
    packet[16..20].copy_from_slice(&original[12..16]);

    let icmp = &mut packet[IPV4_HEADER_LEN..];
    icmp[0] = 3;
    icmp[1] = 4;
    let advertised_mtu = u16::try_from(maximum_packet_size)
        .unwrap_or(u16::MAX)
        .max(68);
    icmp[6..8].copy_from_slice(&advertised_mtu.to_be_bytes());
    icmp[ICMP_ERROR_HEADER_LEN..].copy_from_slice(&original[..quote_len]);
    let icmp_checksum = internet_checksum(icmp);
    icmp[2..4].copy_from_slice(&icmp_checksum.to_be_bytes());

    let header_checksum = internet_checksum(&packet[..IPV4_HEADER_LEN]);
    packet[10..12].copy_from_slice(&header_checksum.to_be_bytes());
    Ok(Bytes::from(packet))
}

fn ipv6_packet_too_big(
    original: &[u8],
    maximum_packet_size: usize,
) -> Result<Bytes, TransportError> {
    if maximum_packet_size < IPV6_MINIMUM_MTU {
        return Err(TransportError::Ipv6MinimumMtuUnavailable(
            maximum_packet_size,
        ));
    }

    let maximum_quote_len = IPV6_MINIMUM_MTU - IPV6_HEADER_LEN - ICMP_ERROR_HEADER_LEN;
    let quote_len = original.len().min(maximum_quote_len);
    let payload_len = ICMP_ERROR_HEADER_LEN + quote_len;
    let mut packet = vec![0_u8; IPV6_HEADER_LEN + payload_len];

    packet[0] = 0x60;
    packet[4..6].copy_from_slice(&(payload_len as u16).to_be_bytes());
    packet[6] = 58;
    packet[7] = 64;
    packet[8..24].copy_from_slice(&original[24..40]);
    packet[24..40].copy_from_slice(&original[8..24]);

    {
        let icmp = &mut packet[IPV6_HEADER_LEN..];
        icmp[0] = 2;
        icmp[1] = 0;
        let advertised_mtu = u32::try_from(maximum_packet_size).unwrap_or(u32::MAX);
        icmp[4..8].copy_from_slice(&advertised_mtu.to_be_bytes());
        icmp[ICMP_ERROR_HEADER_LEN..].copy_from_slice(&original[..quote_len]);
    }
    let checksum = icmpv6_checksum(&packet[8..24], &packet[24..40], &packet[IPV6_HEADER_LEN..]);
    packet[IPV6_HEADER_LEN + 2..IPV6_HEADER_LEN + 4].copy_from_slice(&checksum.to_be_bytes());
    Ok(Bytes::from(packet))
}

fn icmpv6_checksum(source: &[u8], destination: &[u8], icmp: &[u8]) -> u16 {
    let mut sum = 0_u32;
    add_checksum_bytes(&mut sum, source);
    add_checksum_bytes(&mut sum, destination);
    let length = u32::try_from(icmp.len()).unwrap_or(u32::MAX);
    add_checksum_bytes(&mut sum, &length.to_be_bytes());
    add_checksum_bytes(&mut sum, &[0, 0, 0, 58]);
    add_checksum_bytes(&mut sum, icmp);
    finish_checksum(sum)
}

fn internet_checksum(bytes: &[u8]) -> u16 {
    let mut sum = 0_u32;
    add_checksum_bytes(&mut sum, bytes);
    finish_checksum(sum)
}

fn add_checksum_bytes(sum: &mut u32, bytes: &[u8]) {
    let mut chunks = bytes.chunks_exact(2);
    for word in &mut chunks {
        *sum += u32::from(u16::from_be_bytes([word[0], word[1]]));
    }
    if let Some(last) = chunks.remainder().first() {
        *sum += u32::from(*last) << 8;
    }
}

fn finish_checksum(mut sum: u32) -> u16 {
    while sum > 0xffff {
        sum = (sum & 0xffff) + (sum >> 16);
    }
    !(sum as u16)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn composes_ipv4_fragmentation_needed_with_swapped_addresses() {
        let mut original = vec![0_u8; 1_400];
        original[0] = 0x45;
        original[2..4].copy_from_slice(&1_400_u16.to_be_bytes());
        original[8] = 63;
        original[9] = 6;
        original[12..16].copy_from_slice(&[192, 0, 2, 10]);
        original[16..20].copy_from_slice(&[198, 51, 100, 20]);

        let response = packet_too_big(&original, 1_280).unwrap();
        assert!(validate_ip_packet(&response).is_ok());
        assert_eq!(&response[12..16], &[198, 51, 100, 20]);
        assert_eq!(&response[16..20], &[192, 0, 2, 10]);
        assert_eq!(&response[20..22], &[3, 4]);
        assert_eq!(u16::from_be_bytes([response[26], response[27]]), 1_280);
        assert_eq!(internet_checksum(&response[..20]), 0);
        assert_eq!(internet_checksum(&response[20..]), 0);
    }

    #[test]
    fn composes_bounded_ipv6_packet_too_big_with_valid_checksum() {
        let mut original = vec![0_u8; 1_400];
        original[0] = 0x60;
        original[4..6].copy_from_slice(&1_360_u16.to_be_bytes());
        original[6] = 17;
        original[7] = 63;
        original[8..24].copy_from_slice(
            &"2001:db8::10"
                .parse::<std::net::Ipv6Addr>()
                .unwrap()
                .octets(),
        );
        original[24..40].copy_from_slice(
            &"2001:db8::20"
                .parse::<std::net::Ipv6Addr>()
                .unwrap()
                .octets(),
        );

        let response = packet_too_big(&original, 1_280).unwrap();
        assert_eq!(response.len(), IPV6_MINIMUM_MTU);
        assert!(validate_ip_packet(&response).is_ok());
        assert_eq!(&response[40..42], &[2, 0]);
        assert_eq!(
            u32::from_be_bytes([response[44], response[45], response[46], response[47]]),
            1_280
        );
        assert_eq!(
            icmpv6_checksum(&response[8..24], &response[24..40], &response[40..]),
            0
        );
    }

    #[test]
    fn rejects_an_ipv6_path_below_the_protocol_minimum() {
        let mut original = [0_u8; 40];
        original[0] = 0x60;
        assert!(matches!(
            packet_too_big(&original, 1_279),
            Err(TransportError::Ipv6MinimumMtuUnavailable(1_279))
        ));
    }
}
