import 'package:flutter/foundation.dart';

import '../models/app_models.dart';

class AppStrings {
  AppStrings(LocalePreference preference)
    : languageCode = _resolveLanguageCode(preference);

  final String languageCode;

  bool get isChinese => languageCode == 'zh';

  static String _resolveLanguageCode(LocalePreference preference) {
    return switch (preference) {
      LocalePreference.english => 'en',
      LocalePreference.simplifiedChinese => 'zh',
      LocalePreference.system =>
        PlatformDispatcher.instance.locale.languageCode == 'zh' ? 'zh' : 'en',
    };
  }

  String get(String key) {
    final values = isChinese ? _zh : _en;
    return values[key] ?? _en[key] ?? key;
  }

  @visibleForTesting
  static bool get debugCatalogsAreComplete {
    final englishKeys = _en.keys.toSet();
    final chineseKeys = _zh.keys.toSet();
    return setEquals(englishKeys, chineseKeys) &&
        _en.values.every((value) => value.trim().isNotEmpty) &&
        _zh.values.every((value) => value.trim().isNotEmpty);
  }

  static const Map<String, String> _en = <String, String>{
    'app_name': 'Usque',
    'home': 'Home',
    'profiles': 'Profiles',
    'proxy': 'Proxy',
    'settings': 'Settings',
    'diagnostics': 'Diagnostics',
    'status_stream_degraded': 'Live status updates are degraded',
    'status_stream_degraded_body':
        'Status polling is active; live updates will retry automatically.',
    'connect': 'Connect',
    'disconnect': 'Disconnect',
    'connecting': 'Connecting…',
    'disconnected': 'Disconnected',
    'connected': 'Connected',
    'degraded': 'Connected with limited connectivity',
    'reconnecting': 'Reconnecting…',
    'preparing': 'Preparing secure tunnel…',
    'disconnecting': 'Disconnecting…',
    'error': 'Connection error',
    'active_profile': 'Active profile',
    'protocol': 'Protocol',
    'address_family': 'Address family',
    'duration': 'Duration',
    'download': 'Download',
    'upload': 'Upload',
    'location': 'Location',
    'ipv4': 'IPv4',
    'ipv6': 'IPv6',
    'not_available': 'Not available',
    'engine_unavailable':
        'The native Usque Engine is not available in this build yet.',
    'dismiss': 'Dismiss',
    'new_profile': 'New profile',
    'profile_name': 'Profile name',
    'profile_name_too_long': 'Use no more than 64 characters.',
    'configure_identity': 'Configure WARP identity',
    'identity_ready': 'Identity ready',
    'identity_missing': 'Identity required',
    'identity_invalid': 'Identity needs repair',
    'identity_setup_failed': 'The WARP identity could not be configured.',
    'use_license_key': 'Use a WARP License Key',
    'warp_license_key': 'WARP License Key',
    'show_license': 'Show License Key',
    'hide_license': 'Hide License Key',
    'license_copied': 'License Key copied',
    'warp_secret_saved': 'WARP Secret saved',
    'create': 'Create',
    'cancel': 'Cancel',
    'active': 'Active',
    'set_active': 'Set active',
    'edit': 'Edit',
    'delete': 'Delete',
    'delete_profile': 'Delete profile?',
    'delete_profile_body':
        'This removes the non-secret settings for this profile. Stored identity data is not deleted.',
    'mode': 'Connection mode',
    'vpn_mode': 'VPN',
    'socks_mode': 'SOCKS5',
    'http_mode': 'HTTP',
    'edit_profile': 'Edit profile',
    'tunnel_output': 'VPN / virtual adapter',
    'channel_only': 'MASQUE channel only',
    'channel_only_warning': 'No network output is enabled.',
    'socks_listener': 'SOCKS5 listener',
    'http_listener': 'HTTP listener',
    'listen_ipv4': 'Listen IPv4',
    'listen_ipv6': 'Listen IPv6',
    'port': 'Port',
    'remote_dns': 'Resolve names remotely',
    'proxy_dns_mode': 'Proxy DNS resolution',
    'proxy_dns_remote': 'Remote through tunnel',
    'proxy_dns_configured': 'Custom DNS servers',
    'proxy_dns_system': 'System DNS',
    'dns_leak_warning': 'Local DNS may reveal requested names',
    'dns_leak_warning_body':
        'Custom or system DNS is resolved outside the remote proxy path. Use remote DNS unless you explicitly accept this exposure.',
    'system_proxy': 'Configure system proxy',
    'output_disabled_in_profile': 'Disabled in this Profile',
    'auto_connect': 'Connect this Profile automatically',
    'lan_warning': 'Proxy exposed to the local network',
    'lan_warning_body':
        'Usque does not add username/password authentication. Anyone who can reach this listener may use it.',
    'general': 'General',
    'system_integration': 'System integration',
    'start_on_boot': 'Start Usque when you sign in',
    'close_to_tray': 'Close the window to the system tray',
    'add_quick_settings_tile': 'Add Quick Settings Tile',
    'appearance': 'Appearance',
    'theme': 'Theme',
    'theme_system': 'System',
    'theme_light': 'Light',
    'theme_dark': 'Dark',
    'language': 'Language',
    'language_system': 'System',
    'language_en': 'English',
    'language_zh': '简体中文',
    'updates': 'Updates',
    'check_updates': 'Check for updates',
    'check_now': 'Check now',
    'update_available': 'A newer release is available:',
    'already_latest': 'This installation is already up to date.',
    'open_release': 'Open release page',
    'notice': 'Completed',
    'identity': 'WARP identity',
    'identity_and_license': 'Identity & License',
    'license_cleanup_pending': 'An old device slot is awaiting cleanup.',
    'copy_license': 'Copy License Key',
    'change_license': 'Change License Key',
    'unbind_license': 'Return to free WARP',
    'export_warp_secret': 'Export WARP Secret',
    'close': 'Close',
    'advanced': 'Advanced network settings',
    'advanced_warning':
        'Incorrect endpoints, SNI, DNS, or MTU can prevent the tunnel from connecting.',
    'ip_dns': 'IP & DNS',
    'routing_protection': 'Routing & protection',
    'open_advanced': 'Open advanced settings',
    'transport': 'Transport',
    'automatic': 'Auto',
    'http3': 'HTTP/3',
    'http2': 'HTTP/2',
    'endpoint_ipv4': 'Endpoint IPv4',
    'endpoint_ipv6': 'Endpoint IPv6',
    'sni': 'SNI',
    'mtu': 'MTU',
    'dns_ipv4': 'DNS IPv4',
    'dns_ipv6': 'DNS IPv6',
    'ip_policy': 'Endpoint family',
    'prefer_ipv4': 'Prefer IPv4 endpoint',
    'prefer_ipv6': 'Prefer IPv6 endpoint',
    'ipv4_only': 'IPv4 endpoint only',
    'ipv6_only': 'IPv6 endpoint only',
    'kill_switch': 'Kill Switch',
    'on': 'On',
    'ready': 'Ready',
    'not_used_proxy': 'Not used in proxy mode',
    'kill_switch_help':
        'Block traffic while connecting, reconnecting, or recovering from an engine failure.',
    'allow_lan': 'Allow local network',
    'bypass_cidrs': 'Additional bypass CIDRs',
    'bypass_hint': 'One CIDR per line',
    'reset_defaults': 'Reset network defaults',
    'reset_defaults_body':
        'Restore endpoints, SNI, DNS, MTU, listeners, transport, and endpoint preference?',
    'reset': 'Reset',
    'save': 'Save',
    'saved': 'Saved',
    'invalid_fields': 'Check the highlighted fields.',
    'required': 'Required',
    'invalid_address': 'Invalid address',
    'invalid_dns_name': 'Invalid DNS name',
    'invalid_cidr': 'Invalid CIDR',
    'diagnostics_title': 'Diagnostics & About',
    'engine_status': 'Engine status',
    'version': 'Version',
    'app_version': 'Usque 0.1.2',
    'logs': 'Local logs',
    'export_diagnostics': 'Export diagnostic bundle',
    'diagnostics_saved': 'Diagnostic bundle saved to',
    'export_help':
        'You will review its contents before saving. Secrets, tokens, private keys, and full sensitive addresses are excluded.',
    'source_code': 'Source code',
    'license': 'License',
    'clear_all_data': 'Clear all data',
    'clear_all_data_help':
        'Disconnect and permanently remove every Profile, Consumer WARP identity, preference, cache, and local diagnostic record from this device.',
    'clear_all_data_confirm':
        'This cannot be undone. Usque will disconnect first, erase all saved identities and Profiles, and return to initial setup.',
    'clear_all_data_complete': 'All local Usque data was cleared.',
    'unofficial':
        'Unofficial client compatible with Cloudflare WARP. Not affiliated with or endorsed by Cloudflare.',
    'welcome_title': 'Welcome to Usque',
    'setup_progress': 'Setup step {current} of {total}',
    'get_started': 'Get started',
    'permissions_title': 'System permissions',
    'permissions_body':
        'Usque needs permission to create a VPN interface and manage routes, DNS, firewall rules, and the system proxy.',
    'terms_title': 'Cloudflare terms',
    'terms_body':
        'Usque is an independent client. Your use of Consumer WARP remains subject to Cloudflare’s applicable terms and privacy policy.',
    'terms_accept': 'I understand and accept these conditions.',
    'identity_title': 'Set up Consumer WARP',
    'register_new': 'Register a new identity',
    'manual_secret': 'Enter WARP Secret',
    'warp_secret': 'WARP Secret',
    'show_secret': 'Show secret',
    'hide_secret': 'Hide secret',
    'finish_setup': 'Finish setup',
    'back': 'Back',
    'continue': 'Continue',
    'permission_note':
        'The operating system may show an additional confirmation when you first connect.',
    'setup_failed': 'Setup could not be completed',
    'profile_required': 'Keep at least one profile.',
    'socks_capabilities': 'TCP and UDP',
    'http_capabilities': 'CONNECT and ordinary forwarding',
  };

  static const Map<String, String> _zh = <String, String>{
    'app_name': 'Usque',
    'home': '首页',
    'profiles': '配置',
    'proxy': '代理',
    'settings': '设置',
    'diagnostics': '诊断',
    'status_stream_degraded': '实时状态更新已降级',
    'status_stream_degraded_body': '正在使用状态轮询；实时更新会自动重试。',
    'connect': '连接',
    'disconnect': '断开',
    'connecting': '正在连接…',
    'disconnected': '未连接',
    'connected': '已连接',
    'degraded': '已连接，部分网络受限',
    'reconnecting': '正在重新连接…',
    'preparing': '正在准备安全隧道…',
    'disconnecting': '正在断开…',
    'error': '连接错误',
    'active_profile': '当前配置',
    'protocol': '协议',
    'address_family': '地址族',
    'duration': '持续时间',
    'download': '下载',
    'upload': '上传',
    'location': '位置',
    'ipv4': 'IPv4',
    'ipv6': 'IPv6',
    'not_available': '不可用',
    'engine_unavailable': '此构建尚未提供原生 Usque Engine。',
    'dismiss': '关闭',
    'new_profile': '新建配置',
    'profile_name': '配置名称',
    'profile_name_too_long': '名称不能超过 64 个字符。',
    'configure_identity': '配置 WARP 身份',
    'identity_ready': '身份已就绪',
    'identity_missing': '需要配置身份',
    'identity_invalid': '身份需要修复',
    'identity_setup_failed': '无法配置 WARP 身份。',
    'use_license_key': '使用 WARP License Key',
    'warp_license_key': 'WARP License Key',
    'show_license': '显示 License Key',
    'hide_license': '隐藏 License Key',
    'license_copied': 'License Key 已复制',
    'warp_secret_saved': 'WARP Secret 已保存',
    'create': '创建',
    'cancel': '取消',
    'active': '使用中',
    'set_active': '设为当前',
    'edit': '编辑',
    'delete': '删除',
    'delete_profile': '删除配置？',
    'delete_profile_body': '这会删除此配置的非秘密设置，不会删除系统中保存的身份数据。',
    'mode': '连接模式',
    'vpn_mode': 'VPN',
    'socks_mode': 'SOCKS5',
    'http_mode': 'HTTP',
    'edit_profile': '编辑配置',
    'tunnel_output': 'VPN / 虚拟网卡',
    'channel_only': '仅 MASQUE 通道',
    'channel_only_warning': '未启用网络输出。',
    'socks_listener': 'SOCKS5 监听',
    'http_listener': 'HTTP 监听',
    'listen_ipv4': '监听 IPv4',
    'listen_ipv6': '监听 IPv6',
    'port': '端口',
    'remote_dns': '远程解析域名',
    'proxy_dns_mode': '代理 DNS 解析',
    'proxy_dns_remote': '通过隧道远程解析',
    'proxy_dns_configured': '自定义 DNS 服务器',
    'proxy_dns_system': '使用系统 DNS',
    'dns_leak_warning': '本地 DNS 可能暴露访问的域名',
    'dns_leak_warning_body': '自定义 DNS 或系统 DNS 不经过远端代理解析；除非明确接受该风险，否则请使用远程 DNS。',
    'system_proxy': '配置系统代理',
    'output_disabled_in_profile': '已在此配置中关闭',
    'auto_connect': '自动连接此配置',
    'lan_warning': '代理已暴露到局域网',
    'lan_warning_body': 'Usque 不会添加用户名/密码认证。任何能访问此监听地址的人都可能使用它。',
    'general': '通用',
    'system_integration': '系统集成',
    'start_on_boot': '登录系统时启动 Usque',
    'close_to_tray': '关闭窗口时隐藏到系统托盘',
    'add_quick_settings_tile': '添加快捷设置磁贴',
    'appearance': '外观',
    'theme': '主题',
    'theme_system': '跟随系统',
    'theme_light': '浅色',
    'theme_dark': '深色',
    'language': '语言',
    'language_system': '跟随系统',
    'language_en': 'English',
    'language_zh': '简体中文',
    'updates': '更新',
    'check_updates': '检查更新',
    'check_now': '立即检查',
    'update_available': '发现新版本：',
    'already_latest': '当前版本已是最新版本。',
    'open_release': '打开发布页面',
    'notice': '已完成',
    'identity': 'WARP 身份',
    'identity_and_license': '身份与 License',
    'license_cleanup_pending': '旧设备槽位正等待后台清理。',
    'copy_license': '复制 License Key',
    'change_license': '更换 License Key',
    'unbind_license': '恢复免费 WARP',
    'export_warp_secret': '导出 WARP Secret',
    'close': '关闭',
    'advanced': '高级网络设置',
    'advanced_warning': '错误的端点、SNI、DNS 或 MTU 可能导致隧道无法连接。',
    'ip_dns': 'IP 与 DNS',
    'routing_protection': '路由与保护',
    'open_advanced': '打开高级设置',
    'transport': '传输协议',
    'automatic': '自动',
    'http3': 'HTTP/3',
    'http2': 'HTTP/2',
    'endpoint_ipv4': '端点 IPv4',
    'endpoint_ipv6': '端点 IPv6',
    'sni': 'SNI',
    'mtu': 'MTU',
    'dns_ipv4': 'DNS IPv4',
    'dns_ipv6': 'DNS IPv6',
    'ip_policy': '入口地址族',
    'prefer_ipv4': '优先 IPv4 入口',
    'prefer_ipv6': '优先 IPv6 入口',
    'ipv4_only': '仅使用 IPv4 入口',
    'ipv6_only': '仅使用 IPv6 入口',
    'kill_switch': 'Kill Switch',
    'on': '已开启',
    'ready': '就绪',
    'not_used_proxy': '代理模式不适用',
    'kill_switch_help': '连接、重连或 Engine 故障恢复期间阻止流量泄漏。',
    'allow_lan': '允许访问局域网',
    'bypass_cidrs': '额外绕过 CIDR',
    'bypass_hint': '每行一个 CIDR',
    'reset_defaults': '恢复网络默认值',
    'reset_defaults_body': '恢复端点、SNI、DNS、MTU、监听地址、传输协议和入口偏好？',
    'reset': '恢复',
    'save': '保存',
    'saved': '已保存',
    'invalid_fields': '请检查标出的字段。',
    'required': '必填',
    'invalid_address': '地址无效',
    'invalid_dns_name': 'DNS 名称无效',
    'invalid_cidr': 'CIDR 无效',
    'diagnostics_title': '诊断与关于',
    'engine_status': 'Engine 状态',
    'version': '版本',
    'app_version': 'Usque 0.1.2',
    'logs': '本地日志',
    'export_diagnostics': '导出诊断包',
    'diagnostics_saved': '诊断包已保存至',
    'export_help': '保存前可检查内容；不包含 Secret、Token、私钥和完整敏感地址。',
    'source_code': '源代码',
    'license': '许可证',
    'clear_all_data': '清除全部数据',
    'clear_all_data_help':
        '断开连接，并从此设备永久删除所有 Profile、Consumer WARP 身份、偏好设置、缓存和本地诊断记录。',
    'clear_all_data_confirm':
        '此操作无法撤销。Usque 会先断开连接，清除所有已保存身份和 Profile，然后返回首次设置。',
    'clear_all_data_complete': '已清除全部本地 Usque 数据。',
    'unofficial': '兼容 Cloudflare WARP 的非官方客户端，与 Cloudflare 无隶属或背书关系。',
    'welcome_title': '欢迎使用 Usque',
    'setup_progress': '设置步骤 {current}/{total}',
    'get_started': '开始',
    'permissions_title': '系统权限',
    'permissions_body': 'Usque 需要创建 VPN 接口，以及管理路由、DNS、防火墙规则和系统代理。',
    'terms_title': 'Cloudflare 条款',
    'terms_body': 'Usque 是独立客户端。使用 Consumer WARP 仍须遵守 Cloudflare 适用条款和隐私政策。',
    'terms_accept': '我理解并接受这些条件。',
    'identity_title': '设置 Consumer WARP',
    'register_new': '注册新身份',
    'manual_secret': '输入 WARP Secret',
    'warp_secret': 'WARP Secret',
    'show_secret': '显示 Secret',
    'hide_secret': '隐藏 Secret',
    'finish_setup': '完成设置',
    'back': '返回',
    'continue': '继续',
    'permission_note': '首次连接时，操作系统可能还会显示一次确认。',
    'setup_failed': '设置未能完成',
    'profile_required': '至少保留一个配置。',
    'socks_capabilities': 'TCP 与 UDP',
    'http_capabilities': 'CONNECT 与普通转发',
  };
}
