import 'app_strings.dart';

extension ChainStrings on AppStrings {
  String chain(String key) =>
      (catalogId.startsWith('zh') ? _zh : _en)[key] ??
      _en[key] ??
      _en['invalid_configuration']!;
}

const _en = <String, String>{
  'dns_fallback': 'Tunnel DNS (OpenVPN may negotiate DNS)',
  'dns_unavailable':
      'DNS is outside AllowedIPs. Use IP addresses or reimport a configuration with reachable DNS.',
  'authentication_failed':
      'Authentication failed. Update credentials before connecting again.',
  'profile_limit': 'The configuration library is full (128 profiles).',
  'metadata_limit': 'The configuration library metadata is full.',
  'title': 'Chain proxy',
  'subtitle': 'Choose an exit reached through WARP.',
  'source': 'Exit source',
  'enable': 'Enable chain proxy',
  'import_file': 'Import file',
  'paste': 'Paste configuration',
  'profiles': 'Saved configurations',
  'empty': 'Import a configuration to select an exit.',
  'preview': 'Check configuration',
  'save_import': 'Save configuration',
  'name': 'Name',
  'configuration': 'Configuration text',
  'username': 'Username',
  'password': 'Password',
  'key_password': 'Private key password',
  'credentials': 'Update credentials',
  'rename': 'Rename',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'save': 'Save',
  'apply': 'Apply changes',
  'clear': 'Clear selection',
  'current': 'Current connection',
  'saved': 'Saved selection',
  'draft': 'Pending selection',
  'disconnected': 'Not connected',
  'connected': 'Connected',
  'connecting': 'Connecting',
  'error': 'Connection failed',
  'no_selection': 'No configuration selected',
  'l4': 'This configuration requires CONNECT-IP.',
  'switch_mode': 'Switch to CONNECT-IP and apply',
  'unsupported': 'This engine does not support this chain source.',
  'scope':
      'Existing explicit direct rules still apply. Other traffic uses the selected exit.',
  'allowed': 'Allowed destinations',
  'dns': 'DNS',
  'addresses': 'Tunnel addresses',
  'endpoint': 'Server',
  'restricted':
      'Destinations outside AllowedIPs are blocked on the proxy path.',
  'delete_confirm':
      'Delete this saved configuration? The original imported file is unchanged.',
  'profile_in_use':
      'Choose another configuration or clear the saved selection before deleting this configuration.',
  'stale_revision':
      'The configuration changed. Refresh the list and try again.',
  'secure_storage_failed':
      'The encrypted configuration could not be read or saved.',
  'invalid_configuration':
      'The configuration is invalid or contains unsupported options.',
  'file_unavailable':
      'A file picker is unavailable. Paste the configuration text instead.',
  'invalid_size_or_encoding':
      'Use a UTF-8 configuration no larger than 128 KiB.',
  'unsupported_directive': 'This OpenVPN directive is not supported.',
  'unsupported_or_duplicate_field': 'This field is unsupported or duplicated.',
  'unsupported_or_duplicate_section': 'Use one Interface and one Peer section.',
  'missing_field': 'A required field is missing.',
  'invalid_key': 'The key must be a valid 32-byte Base64 key.',
  'checking': 'Checking configuration…',
  'changed': 'Changes saved',
};
const _zh = <String, String>{
  'dns_fallback': '现有隧道 DNS（OpenVPN 可由服务器协商）',
  'dns_unavailable': 'DNS 不在 AllowedIPs 范围内。请使用 IP 地址，或重新导入包含可达 DNS 的配置。',
  'authentication_failed': '认证失败，请更新认证信息后重新连接。',
  'profile_limit': '配置库已满（最多 128 份配置）。',
  'metadata_limit': '配置库元数据已达到容量上限。',
  'title': '链式代理',
  'subtitle': '选择通过 WARP 连接的最终出口。',
  'source': '出口来源',
  'enable': '启用链式代理',
  'import_file': '导入文件',
  'paste': '粘贴配置',
  'profiles': '已保存的配置',
  'empty': '导入配置后即可选择出口。',
  'preview': '检查配置',
  'save_import': '保存配置',
  'name': '名称',
  'configuration': '配置文本',
  'username': '用户名',
  'password': '密码',
  'key_password': '私钥口令',
  'credentials': '更新认证信息',
  'rename': '重命名',
  'delete': '删除',
  'cancel': '取消',
  'save': '保存',
  'apply': '应用更改',
  'clear': '清除选择',
  'current': '当前连接',
  'saved': '已保存的选择',
  'draft': '待应用的选择',
  'disconnected': '未连接',
  'connected': '已连接',
  'connecting': '正在连接',
  'error': '连接失败',
  'no_selection': '尚未选择配置',
  'l4': '此配置需要 CONNECT-IP 模式。',
  'switch_mode': '切换为 CONNECT-IP 并应用',
  'unsupported': '当前引擎不支持此出口来源。',
  'scope': '现有显式直连规则继续生效，其他流量使用所选出口。',
  'allowed': '允许访问的目标',
  'dns': 'DNS',
  'addresses': '隧道地址',
  'endpoint': '服务器',
  'restricted': '代理路径会拒绝 AllowedIPs 范围之外的目标。',
  'delete_confirm': '删除此已保存配置？原始导入文件保持不变。',
  'profile_in_use': '请先选择其他配置或清除已保存的选择，再删除此配置。',
  'stale_revision': '配置已发生变化，请刷新列表后重试。',
  'secure_storage_failed': '无法读取或保存加密配置。',
  'invalid_configuration': '配置无效或包含不支持的选项。',
  'file_unavailable': '文件选择器不可用，请改用粘贴配置。',
  'invalid_size_or_encoding': '请使用不超过 128 KiB 的 UTF-8 配置。',
  'unsupported_directive': '不支持此 OpenVPN 指令。',
  'unsupported_or_duplicate_field': '此字段不受支持或重复出现。',
  'unsupported_or_duplicate_section': '配置只允许一个 Interface 和一个 Peer。',
  'missing_field': '缺少必需字段。',
  'invalid_key': '密钥必须是有效的 32 字节 Base64 密钥。',
  'checking': '正在检查配置…',
  'changed': '更改已保存',
};
