import 'app_strings.dart';

extension ChainStrings on AppStrings {
  String chain(String key) =>
      (_catalogs[catalogId] ?? _en)[key] ??
      _en[key] ??
      _en['invalid_configuration']!;

  /// Human-readable location for a validation error reported by the engine.
  ///
  /// Field and line come from the validator; configuration values are never
  /// reproduced. Missing parts are omitted rather than shown as blanks.
  String chainError(Map<String, Object?> error) {
    final message = chain(
      error['reason'] as String? ?? 'invalid_configuration',
    );
    final field = switch (error['field']) {
      final String value when value.trim().isNotEmpty => value.trim(),
      _ => null,
    };
    final line = switch (error['line']) {
      final int value when value > 0 => value,
      _ => null,
    };
    if (field == null) return message;
    return chain(line == null ? 'error_field' : 'error_location')
        .replaceAll('{message}', message)
        .replaceAll('{field}', field)
        .replaceAll('{line}', '${line ?? ''}');
  }
}

const _catalogs = <String, Map<String, String>>{
  'en': _en,
  'zh_CN': _zh,
  'zh_TW': _zhHant,
  'zh_HK': _zhHant,
};

const _en = <String, String>{
  'duplicate_directive': 'This directive may appear only once.',
  'mixed_protocols':
      'All remote endpoints must use the same TCP or UDP transport.',
  'conflicting_protocol': 'The remote and global transport settings conflict.',
  'too_many_endpoints': 'Use no more than 16 remote endpoints.',
  'conflicting_authentication':
      'CLIENT_CERT conflicts with the inline certificate or authentication mode.',
  'serialized_size_limit':
      'The encrypted record would exceed the storage size limit.',
  'multi_endpoint_unavailable':
      'Update the engine to use configurations with multiple endpoints.',
  'candidates': 'Startup endpoints',
  'random_order': 'Try endpoints in a new random order for each connection.',
  'file_order': 'Try endpoints in file order.',
  'attempting': 'Trying endpoint',
  'actual_endpoint': 'Connected endpoint',
  'attempt_failures': 'Failed attempts',
  'failure_transport': 'transport closed',
  'failure_authentication': 'authentication',
  'failure_certificate': 'certificate',
  'failure_configuration': 'configuration',
  'failure_address_changed': 'address changed',
  'failure_protocol': 'protocol',
  'failure_cleanup': 'cleanup',
  'failure_reason': 'Failure: {reason}.',
  'manage': 'Manage',

  'dns_fallback': 'Tunnel DNS (OpenVPN may negotiate DNS)',
  'dns_unavailable_title': 'No DNS through this exit',
  'dns_unavailable':
      'No DNS server is reachable through this exit. Use IP addresses or reimport a configuration with reachable DNS.',
  'authentication_failed':
      'Authentication failed. Update credentials before connecting again.',
  'profile_limit': 'The configuration library is full (128 profiles).',
  'metadata_limit': 'The configuration library metadata is full.',
  'title': 'Chain proxy',
  'subtitle': 'Choose an exit reached through WARP.',
  'source': 'Exit source',
  'enable': 'Enable chain proxy',
  'import_file': 'Import file',
  'paste': 'Paste configuration',
  'profiles': 'Saved configurations',
  'empty': 'Import a configuration to select an exit.',
  'empty_hint_openvpn':
      'Import a .ovpn file or paste its text. TCP and UDP endpoints, inline certificates and username/password are supported.',
  'empty_hint_wireguard':
      'Import a .conf file or paste its text. One [Interface] and one [Peer] section are supported.',
  'import_limits':
      'Configurations must be UTF-8 text up to 128 KiB. Devices without a file picker can paste the text instead.',
  'enable_to_choose': 'Enable chain proxy to select a configuration.',
  'select_required': 'Select a saved configuration to apply.',
  'pending_disable': 'Pending: disable chain proxy',
  'apply_reconnect': 'Apply and reconnect',
  'requires_connect_ip': 'Requires CONNECT-IP',
  'menu': 'Configuration actions',
  'preview': 'Check configuration',
  'save_import': 'Save configuration',
  'name': 'Name',
  'configuration': 'Configuration text',
  'file_loaded': 'Configuration loaded from file ({lines} lines).',
  'username': 'Username',
  'password': 'Password',
  'key_password': 'Private key password',
  'show_password': 'Show password',
  'hide_password': 'Hide password',
  'credentials': 'Update credentials',
  'rename': 'Rename',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'save': 'Save',
  'apply': 'Apply changes',
  'clear': 'Clear selection',
  'current': 'Current connection',
  'saved': 'Saved selection',
  'draft': 'Pending selection',
  'disconnected': 'Not connected',
  'disabled': 'Not enabled',
  'enabled_idle': 'Enabled · not connected',
  'disconnecting': 'Disconnecting',
  'file_read_failed': 'The configuration file could not be read.',
  'file_encoding_invalid': 'The configuration file must use UTF-8 text.',
  'file_busy': 'A file picker is already open.',
  'connected': 'Connected',
  'connecting': 'Connecting',
  'error': 'Connection failed',
  'no_selection': 'No configuration selected',
  'l4': 'This configuration requires CONNECT-IP.',
  'switch_mode': 'Switch to CONNECT-IP and apply',
  'unsupported': 'This engine does not support this chain source.',
  'scope':
      'Existing explicit direct rules still apply. Other traffic uses the selected exit.',
  'allowed': 'Allowed destinations',
  'dns': 'DNS',
  'addresses': 'Tunnel addresses',
  'address_family': 'Address family',
  'transport': 'Transport',
  'endpoint': 'Server',
  'restricted':
      'Destinations outside AllowedIPs are blocked on the proxy path.',
  'delete_confirm':
      'Delete this saved configuration? The original imported file is unchanged.',
  'profile_in_use':
      'Choose another configuration or clear the saved selection before deleting this configuration.',
  'stale_revision':
      'The configuration changed. Refresh the list and try again.',
  'secure_storage_failed':
      'The encrypted configuration could not be read or saved.',
  'invalid_configuration':
      'The configuration is invalid or contains unsupported options.',
  'looks_like_wireguard':
      'This looks like a WireGuard configuration. Switch the exit source to WireGuard (Custom).',
  'looks_like_openvpn':
      'This looks like an OpenVPN configuration. Switch the exit source to OpenVPN (Custom).',
  'error_location': '{message} ({field}, line {line})',
  'error_field': '{message} ({field})',
  'file_unavailable':
      'A file picker is unavailable. Paste the configuration text instead.',
  'invalid_size_or_encoding':
      'Use a UTF-8 configuration no larger than 128 KiB.',
  'unsupported_directive': 'This OpenVPN directive is not supported.',
  'unsupported_or_duplicate_field': 'This field is unsupported or duplicated.',
  'unsupported_or_duplicate_section': 'Use one Interface and one Peer section.',
  'missing_field': 'A required field is missing.',
  'invalid_key': 'The key must be a valid 32-byte Base64 key.',
  'checking': 'Checking configuration…',
  'changed': 'Changes saved',
};

const _zh = <String, String>{
  'duplicate_directive': '此指令只能出现一次。',
  'mixed_protocols': '所有 remote 端点必须统一使用 TCP 或 UDP。',
  'conflicting_protocol': 'remote 与全局传输协议设置冲突。',
  'too_many_endpoints': '最多支持 16 个 remote 端点。',
  'conflicting_authentication': 'CLIENT_CERT 与内嵌证书或认证方式冲突。',
  'serialized_size_limit': '加密记录将超过存储大小上限。',
  'multi_endpoint_unavailable': '请更新引擎后使用多端点配置。',
  'candidates': '启动候选端点',
  'random_order': '每次连接以新的随机顺序尝试候选端点。',
  'file_order': '按配置文件顺序尝试候选端点。',
  'attempting': '正在尝试端点',
  'actual_endpoint': '实际连接端点',
  'attempt_failures': '失败的尝试',
  'failure_transport': '传输中断',
  'failure_authentication': '认证',
  'failure_certificate': '证书',
  'failure_configuration': '配置',
  'failure_address_changed': '地址变化',
  'failure_protocol': '协议',
  'failure_cleanup': '清理',
  'failure_reason': '故障原因：{reason}。',
  'manage': '管理',

  'dns_fallback': '现有隧道 DNS（OpenVPN 可由服务器协商）',
  'dns_unavailable_title': '此出口没有可用 DNS',
  'dns_unavailable': '此出口没有可达的 DNS 服务器。请使用 IP 地址，或重新导入包含可达 DNS 的配置。',
  'authentication_failed': '认证失败，请更新认证信息后重新连接。',
  'profile_limit': '配置库已满（最多 128 份配置）。',
  'metadata_limit': '配置库元数据已达到容量上限。',
  'title': '链式代理',
  'subtitle': '选择通过 WARP 连接的最终出口。',
  'source': '出口来源',
  'enable': '启用链式代理',
  'import_file': '导入文件',
  'paste': '粘贴配置',
  'profiles': '已保存的配置',
  'empty': '导入配置后即可选择出口。',
  'empty_hint_openvpn': '导入 .ovpn 文件或粘贴其文本。支持 TCP/UDP 端点、内嵌证书和用户名/密码。',
  'empty_hint_wireguard': '导入 .conf 文件或粘贴其文本。支持一个 [Interface] 和一个 [Peer]。',
  'import_limits': '配置须为不超过 128 KiB 的 UTF-8 文本。没有文件选择器的设备可以改为粘贴文本。',
  'enable_to_choose': '启用链式代理后即可选择配置。',
  'select_required': '请选择一份已保存的配置后再应用。',
  'pending_disable': '待应用：关闭链式代理',
  'apply_reconnect': '应用并重新连接',
  'requires_connect_ip': '需要 CONNECT-IP',
  'menu': '配置操作',
  'preview': '检查配置',
  'save_import': '保存配置',
  'name': '名称',
  'configuration': '配置文本',
  'file_loaded': '已从文件读取配置（{lines} 行）。',
  'username': '用户名',
  'password': '密码',
  'key_password': '私钥口令',
  'show_password': '显示密码',
  'hide_password': '隐藏密码',
  'credentials': '更新认证信息',
  'rename': '重命名',
  'delete': '删除',
  'cancel': '取消',
  'save': '保存',
  'apply': '应用更改',
  'clear': '清除选择',
  'current': '当前连接',
  'saved': '已保存的选择',
  'draft': '待应用的选择',
  'disconnected': '未连接',
  'disabled': '未启用',
  'enabled_idle': '已启用 · 未连接',
  'disconnecting': '正在断开',
  'file_read_failed': '无法读取配置文件。',
  'file_encoding_invalid': '配置文件必须使用 UTF-8 编码。',
  'file_busy': '文件选择器已经打开。',
  'connected': '已连接',
  'connecting': '正在连接',
  'error': '连接失败',
  'no_selection': '尚未选择配置',
  'l4': '此配置需要 CONNECT-IP 模式。',
  'switch_mode': '切换为 CONNECT-IP 并应用',
  'unsupported': '当前引擎不支持此出口来源。',
  'scope': '现有显式直连规则继续生效，其他流量使用所选出口。',
  'allowed': '允许访问的目标',
  'dns': 'DNS',
  'addresses': '隧道地址',
  'address_family': '地址族',
  'transport': '传输协议',
  'endpoint': '服务器',
  'restricted': '代理路径会拒绝 AllowedIPs 范围之外的目标。',
  'delete_confirm': '删除此已保存配置？原始导入文件保持不变。',
  'profile_in_use': '请先选择其他配置或清除已保存的选择，再删除此配置。',
  'stale_revision': '配置已发生变化，请刷新列表后重试。',
  'secure_storage_failed': '无法读取或保存加密配置。',
  'invalid_configuration': '配置无效或包含不支持的选项。',
  'looks_like_wireguard': '这看起来是 WireGuard 配置，请将出口来源切换为 WireGuard (Custom)。',
  'looks_like_openvpn': '这看起来是 OpenVPN 配置，请将出口来源切换为 OpenVPN (Custom)。',
  'error_location': '{message}（{field}，第 {line} 行）',
  'error_field': '{message}（{field}）',
  'file_unavailable': '文件选择器不可用，请改用粘贴配置。',
  'invalid_size_or_encoding': '请使用不超过 128 KiB 的 UTF-8 配置。',
  'unsupported_directive': '不支持此 OpenVPN 指令。',
  'unsupported_or_duplicate_field': '此字段不受支持或重复出现。',
  'unsupported_or_duplicate_section': '配置只允许一个 Interface 和一个 Peer。',
  'missing_field': '缺少必需字段。',
  'invalid_key': '密钥必须是有效的 32 字节 Base64 密钥。',
  'checking': '正在检查配置…',
  'changed': '更改已保存',
};

const _zhHant = <String, String>{
  'duplicate_directive': '此指令只能出現一次。',
  'mixed_protocols': '所有 remote 端點必須統一使用 TCP 或 UDP。',
  'conflicting_protocol': 'remote 與全域傳輸協定設定衝突。',
  'too_many_endpoints': '最多支援 16 個 remote 端點。',
  'conflicting_authentication': 'CLIENT_CERT 與內嵌憑證或驗證方式衝突。',
  'serialized_size_limit': '加密記錄將超過儲存大小上限。',
  'multi_endpoint_unavailable': '請更新引擎後再使用多端點設定。',
  'candidates': '啟動候選端點',
  'random_order': '每次連線以新的隨機順序嘗試候選端點。',
  'file_order': '依設定檔順序嘗試候選端點。',
  'attempting': '正在嘗試端點',
  'actual_endpoint': '實際連線端點',
  'attempt_failures': '失敗的嘗試',
  'failure_transport': '傳輸中斷',
  'failure_authentication': '驗證',
  'failure_certificate': '憑證',
  'failure_configuration': '設定',
  'failure_address_changed': '位址變更',
  'failure_protocol': '協定',
  'failure_cleanup': '清理',
  'failure_reason': '故障原因：{reason}。',
  'manage': '管理',

  'dns_fallback': '現有通道 DNS（OpenVPN 可由伺服器協商）',
  'dns_unavailable_title': '此出口沒有可用 DNS',
  'dns_unavailable': '此出口沒有可達的 DNS 伺服器。請使用 IP 位址，或重新匯入包含可達 DNS 的設定。',
  'authentication_failed': '驗證失敗，請更新驗證資訊後重新連線。',
  'profile_limit': '設定庫已滿（最多 128 份設定）。',
  'metadata_limit': '設定庫中繼資料已達容量上限。',
  'title': '鏈式代理',
  'subtitle': '選擇透過 WARP 連線的最終出口。',
  'source': '出口來源',
  'enable': '啟用鏈式代理',
  'import_file': '匯入檔案',
  'paste': '貼上設定',
  'profiles': '已儲存的設定',
  'empty': '匯入設定後即可選擇出口。',
  'empty_hint_openvpn': '匯入 .ovpn 檔案或貼上其文字。支援 TCP/UDP 端點、內嵌憑證和使用者名稱/密碼。',
  'empty_hint_wireguard': '匯入 .conf 檔案或貼上其文字。支援一個 [Interface] 和一個 [Peer]。',
  'import_limits': '設定須為不超過 128 KiB 的 UTF-8 文字。沒有檔案選擇器的裝置可改為貼上文字。',
  'enable_to_choose': '啟用鏈式代理後即可選擇設定。',
  'select_required': '請先選擇一份已儲存的設定再套用。',
  'pending_disable': '待套用：關閉鏈式代理',
  'apply_reconnect': '套用並重新連線',
  'requires_connect_ip': '需要 CONNECT-IP',
  'menu': '設定操作',
  'preview': '檢查設定',
  'save_import': '儲存設定',
  'name': '名稱',
  'configuration': '設定文字',
  'file_loaded': '已從檔案讀取設定（{lines} 行）。',
  'username': '使用者名稱',
  'password': '密碼',
  'key_password': '私鑰密碼',
  'show_password': '顯示密碼',
  'hide_password': '隱藏密碼',
  'credentials': '更新驗證資訊',
  'rename': '重新命名',
  'delete': '刪除',
  'cancel': '取消',
  'save': '儲存',
  'apply': '套用變更',
  'clear': '清除選擇',
  'current': '目前連線',
  'saved': '已儲存的選擇',
  'draft': '待套用的選擇',
  'disconnected': '未連線',
  'disabled': '未啟用',
  'enabled_idle': '已啟用 · 未連線',
  'disconnecting': '正在中斷連線',
  'file_read_failed': '無法讀取設定檔。',
  'file_encoding_invalid': '設定檔必須使用 UTF-8 編碼。',
  'file_busy': '檔案選擇器已經開啟。',
  'connected': '已連線',
  'connecting': '正在連線',
  'error': '連線失敗',
  'no_selection': '尚未選擇設定',
  'l4': '此設定需要 CONNECT-IP 模式。',
  'switch_mode': '切換為 CONNECT-IP 並套用',
  'unsupported': '目前引擎不支援此出口來源。',
  'scope': '現有明確直連規則繼續生效，其他流量使用所選出口。',
  'allowed': '允許存取的目標',
  'dns': 'DNS',
  'addresses': '通道位址',
  'address_family': '位址族',
  'transport': '傳輸協定',
  'endpoint': '伺服器',
  'restricted': '代理路徑會拒絕 AllowedIPs 範圍之外的目標。',
  'delete_confirm': '刪除此已儲存設定？原始匯入檔案保持不變。',
  'profile_in_use': '請先選擇其他設定或清除已儲存的選擇，再刪除此設定。',
  'stale_revision': '設定已變更，請重新整理清單後再試。',
  'secure_storage_failed': '無法讀取或儲存加密設定。',
  'invalid_configuration': '設定無效或包含不支援的選項。',
  'looks_like_wireguard': '這看起來是 WireGuard 設定，請將出口來源切換為 WireGuard (Custom)。',
  'looks_like_openvpn': '這看起來是 OpenVPN 設定，請將出口來源切換為 OpenVPN (Custom)。',
  'error_location': '{message}（{field}，第 {line} 行）',
  'error_field': '{message}（{field}）',
  'file_unavailable': '檔案選擇器無法使用，請改用貼上設定。',
  'invalid_size_or_encoding': '請使用不超過 128 KiB 的 UTF-8 設定。',
  'unsupported_directive': '不支援此 OpenVPN 指令。',
  'unsupported_or_duplicate_field': '此欄位不受支援或重複出現。',
  'unsupported_or_duplicate_section': '設定只允許一個 Interface 和一個 Peer。',
  'missing_field': '缺少必要欄位。',
  'invalid_key': '金鑰必須是有效的 32 位元組 Base64 金鑰。',
  'checking': '正在檢查設定…',
  'changed': '變更已儲存',
};
