import 'app_strings.dart';

// All supported catalogs carry the same compact scanner vocabulary. Shared
// actions (cancel, reset, port) continue to use the application's main catalog.
const _keys = [
  'generate',
  'scan',
  'quick',
  'target',
  'full',
  'pause',
  'resume',
  'country',
  'history',
  'more',
  'observed',
  'unknown',
  'running',
  'paused',
  'completed',
  'cancelled',
  'failed',
  'all',
  'stale',
  'unavailable',
  'hint',
  'full_hint',
];
const kWarpCatalogs = <String, List<String>>{
  'en': [
    'Generate WARP configuration',
    'Scan endpoints',
    'Quick scan',
    'Scan one IP',
    'Complete IPv4 pool',
    'Pause',
    'Resume',
    'Country / region',
    'Scan history',
    'Next page',
    'Observed',
    'Unknown',
    'Scanning',
    'Paused',
    'Complete',
    'Cancelled',
    'Failed',
    'All countries',
    'The outer connection changed. Start a new scan.',
    'Check your WARP account and MASQUE connection, then retry.',
    'Countries are Cloudflare observations from a separate scan identity. Your configuration is checked again when connected.',
    'A complete scan may take days. Progress is saved; resume it manually.',
  ],
  'zh_CN': [
    '生成 WARP 配置',
    '扫描端点',
    '快速扫描',
    '指定 IP 深扫',
    '完整 IPv4 地址池',
    '暂停',
    '继续扫描',
    '国家／地区',
    '扫描历史',
    '下一页',
    '观测时间',
    '未知',
    '扫描中',
    '已暂停',
    '已完成',
    '已取消',
    '失败',
    '全部国家／地区',
    '外层连接条件已变化，请开始新的扫描。',
    '请检查 WARP 账号和 MASQUE 连接后重试。',
    '国家信息来自独立扫描身份的 Cloudflare 观测。使用你的配置连接后会重新测量。',
    '完整扫描可能持续数天。进度会保存，之后可手动续扫。',
  ],
  'zh_HK': [
    '產生 WARP 設定',
    '掃描端點',
    '快速掃描',
    '指定 IP 深度掃描',
    '完整 IPv4 位址池',
    '暫停',
    '繼續掃描',
    '國家／地區',
    '掃描記錄',
    '下一頁',
    '觀測時間',
    '未知',
    '掃描中',
    '已暫停',
    '已完成',
    '已取消',
    '失敗',
    '所有國家／地區',
    '外層連線條件已改變，請開始新的掃描。',
    '請檢查 WARP 帳戶和 MASQUE 連線後重試。',
    '國家資料來自獨立掃描身分的 Cloudflare 觀測。使用你的設定連線後會重新測量。',
    '完整掃描可能持續數天。進度會儲存，之後可手動繼續。',
  ],
  'zh_TW': [
    '產生 WARP 設定',
    '掃描端點',
    '快速掃描',
    '指定 IP 深度掃描',
    '完整 IPv4 位址池',
    '暫停',
    '繼續掃描',
    '國家／地區',
    '掃描紀錄',
    '下一頁',
    '觀測時間',
    '未知',
    '掃描中',
    '已暫停',
    '已完成',
    '已取消',
    '失敗',
    '所有國家／地區',
    '外層連線條件已變更，請開始新的掃描。',
    '請檢查 WARP 帳號和 MASQUE 連線後重試。',
    '國家資訊來自獨立掃描身分的 Cloudflare 觀測。使用你的設定連線後會重新測量。',
    '完整掃描可能持續數天。進度會儲存，之後可手動繼續。',
  ],
  'ja': [
    'WARP 設定を生成',
    'エンドポイントをスキャン',
    '簡易スキャン',
    '指定 IP をスキャン',
    'IPv4 プール全体',
    '一時停止',
    '再開',
    '国・地域',
    'スキャン履歴',
    '次のページ',
    '観測日時',
    '不明',
    'スキャン中',
    '一時停止中',
    '完了',
    'キャンセル済み',
    '失敗',
    'すべての国',
    '外側の接続が変わりました。新しいスキャンを開始してください。',
    'WARP アカウントと MASQUE 接続を確認して再試行してください。',
    '国は専用スキャン ID に対する Cloudflare の観測です。接続時に自分の設定で再測定します。',
    '完全スキャンには数日かかる場合があります。進捗を保存し、手動で再開できます。',
  ],
  'ko': [
    'WARP 구성 생성',
    '엔드포인트 검색',
    '빠른 검색',
    '단일 IP 검색',
    '전체 IPv4 풀',
    '일시 중지',
    '계속',
    '국가 / 지역',
    '검색 기록',
    '다음 페이지',
    '관측 시간',
    '알 수 없음',
    '검색 중',
    '일시 중지됨',
    '완료',
    '취소됨',
    '실패',
    '모든 국가',
    '외부 연결이 변경되었습니다. 새 검색을 시작하세요.',
    'WARP 계정과 MASQUE 연결을 확인하고 다시 시도하세요.',
    '국가는 별도 검색 ID에 대한 Cloudflare 관측값입니다. 연결 시 사용자 구성으로 다시 측정합니다.',
    '전체 검색에는 며칠이 걸릴 수 있습니다. 진행 상황이 저장되며 수동으로 계속할 수 있습니다.',
  ],
  'de': [
    'WARP-Konfiguration erstellen',
    'Endpunkte suchen',
    'Schnellsuche',
    'Eine IP prüfen',
    'Gesamter IPv4-Pool',
    'Pausieren',
    'Fortsetzen',
    'Land / Region',
    'Suchverlauf',
    'Nächste Seite',
    'Beobachtet',
    'Unbekannt',
    'Suche läuft',
    'Pausiert',
    'Abgeschlossen',
    'Abgebrochen',
    'Fehlgeschlagen',
    'Alle Länder',
    'Die äußere Verbindung hat sich geändert. Neue Suche starten.',
    'WARP-Konto und MASQUE-Verbindung prüfen und erneut versuchen.',
    'Länder sind Cloudflare-Beobachtungen einer separaten Scan-Identität. Beim Verbinden wird Ihre Konfiguration erneut geprüft.',
    'Die vollständige Suche kann Tage dauern. Der Fortschritt wird gespeichert und manuell fortgesetzt.',
  ],
  'fr': [
    'Créer une configuration WARP',
    'Rechercher des points de terminaison',
    'Recherche rapide',
    'Analyser une IP',
    'Pool IPv4 complet',
    'Pause',
    'Reprendre',
    'Pays / région',
    'Historique',
    'Page suivante',
    'Observation',
    'Inconnu',
    'Recherche en cours',
    'En pause',
    'Terminé',
    'Annulé',
    'Échec',
    'Tous les pays',
    'La connexion externe a changé. Lancez une nouvelle recherche.',
    'Vérifiez votre compte WARP et la connexion MASQUE, puis réessayez.',
    'Les pays sont observés par Cloudflare avec une identité dédiée. Votre configuration est vérifiée à la connexion.',
    'Une recherche complète peut durer plusieurs jours. La progression est enregistrée ; reprenez manuellement.',
  ],
  'es': [
    'Generar configuración WARP',
    'Buscar endpoints',
    'Búsqueda rápida',
    'Analizar una IP',
    'Todo el grupo IPv4',
    'Pausar',
    'Reanudar',
    'País / región',
    'Historial',
    'Página siguiente',
    'Observado',
    'Desconocido',
    'Buscando',
    'En pausa',
    'Completado',
    'Cancelado',
    'Error',
    'Todos los países',
    'La conexión exterior cambió. Inicia una nueva búsqueda.',
    'Comprueba la cuenta WARP y la conexión MASQUE e inténtalo de nuevo.',
    'Los países son observaciones de Cloudflare con una identidad de búsqueda separada. Tu configuración se comprueba al conectar.',
    'La búsqueda completa puede tardar días. El progreso se guarda; reanuda manualmente.',
  ],
  'pt': [
    'Gerar configuração WARP',
    'Procurar endpoints',
    'Pesquisa rápida',
    'Analisar um IP',
    'Todo o conjunto IPv4',
    'Pausar',
    'Retomar',
    'País / região',
    'Histórico',
    'Próxima página',
    'Observado',
    'Desconhecido',
    'Pesquisando',
    'Pausado',
    'Concluído',
    'Cancelado',
    'Falhou',
    'Todos os países',
    'A ligação externa mudou. Inicie uma nova pesquisa.',
    'Verifique a conta WARP e a ligação MASQUE e tente novamente.',
    'Os países são observações da Cloudflare com uma identidade de pesquisa separada. A configuração é verificada ao ligar.',
    'A pesquisa completa pode demorar dias. O progresso é guardado; retome manualmente.',
  ],
  'nl': [
    'WARP-configuratie maken',
    'Eindpunten zoeken',
    'Snel zoeken',
    'Eén IP scannen',
    'Volledige IPv4-pool',
    'Pauzeren',
    'Hervatten',
    'Land / regio',
    'Scangeschiedenis',
    'Volgende pagina',
    'Waargenomen',
    'Onbekend',
    'Bezig met zoeken',
    'Gepauzeerd',
    'Voltooid',
    'Geannuleerd',
    'Mislukt',
    'Alle landen',
    'De buitenste verbinding is gewijzigd. Start een nieuwe scan.',
    'Controleer uw WARP-account en MASQUE-verbinding en probeer opnieuw.',
    'Landen zijn Cloudflare-waarnemingen met een aparte scanidentiteit. Uw configuratie wordt bij verbinding opnieuw gemeten.',
    'Een volledige scan kan dagen duren. Voortgang wordt opgeslagen; hervat handmatig.',
  ],
  'it': [
    'Genera configurazione WARP',
    'Cerca endpoint',
    'Scansione rapida',
    'Scansiona un IP',
    'Intero pool IPv4',
    'Pausa',
    'Riprendi',
    'Paese / regione',
    'Cronologia',
    'Pagina successiva',
    'Osservato',
    'Sconosciuto',
    'Scansione in corso',
    'In pausa',
    'Completato',
    'Annullato',
    'Non riuscito',
    'Tutti i paesi',
    'La connessione esterna è cambiata. Avvia una nuova scansione.',
    'Controlla account WARP e connessione MASQUE, poi riprova.',
    'I paesi sono osservazioni Cloudflare con una identità di scansione separata. La configurazione viene verificata alla connessione.',
    'La scansione completa può richiedere giorni. I progressi sono salvati; riprendi manualmente.',
  ],
  'ru': [
    'Создать конфигурацию WARP',
    'Поиск узлов',
    'Быстрое сканирование',
    'Сканировать один IP',
    'Весь пул IPv4',
    'Пауза',
    'Продолжить',
    'Страна / регион',
    'История',
    'Следующая страница',
    'Время проверки',
    'Неизвестно',
    'Сканирование',
    'Приостановлено',
    'Завершено',
    'Отменено',
    'Ошибка',
    'Все страны',
    'Внешнее соединение изменилось. Начните новое сканирование.',
    'Проверьте учётную запись WARP и соединение MASQUE и повторите попытку.',
    'Страны определяются Cloudflare для отдельной учётной записи сканирования. Ваша конфигурация проверяется при подключении.',
    'Полное сканирование может занять несколько дней. Прогресс сохраняется; продолжение вручную.',
  ],
  'uk': [
    'Створити конфігурацію WARP',
    'Пошук вузлів',
    'Швидке сканування',
    'Сканувати одну IP',
    'Увесь пул IPv4',
    'Пауза',
    'Продовжити',
    'Країна / регіон',
    'Історія',
    'Наступна сторінка',
    'Час перевірки',
    'Невідомо',
    'Сканування',
    'Призупинено',
    'Завершено',
    'Скасовано',
    'Помилка',
    'Усі країни',
    'Зовнішнє з’єднання змінилося. Почніть нове сканування.',
    'Перевірте обліковий запис WARP і з’єднання MASQUE та спробуйте знову.',
    'Країни визначає Cloudflare для окремої особи сканування. Ваша конфігурація перевіряється під час підключення.',
    'Повне сканування може тривати кілька днів. Прогрес зберігається; продовження вручну.',
  ],
  'pl': [
    'Utwórz konfigurację WARP',
    'Szukaj punktów końcowych',
    'Szybkie skanowanie',
    'Skanuj jeden IP',
    'Cała pula IPv4',
    'Wstrzymaj',
    'Wznów',
    'Kraj / region',
    'Historia',
    'Następna strona',
    'Czas obserwacji',
    'Nieznany',
    'Skanowanie',
    'Wstrzymano',
    'Ukończono',
    'Anulowano',
    'Błąd',
    'Wszystkie kraje',
    'Połączenie zewnętrzne się zmieniło. Rozpocznij nowe skanowanie.',
    'Sprawdź konto WARP i połączenie MASQUE, a następnie ponów próbę.',
    'Kraje są obserwowane przez Cloudflare z osobną tożsamością skanowania. Konfiguracja jest sprawdzana przy połączeniu.',
    'Pełne skanowanie może trwać kilka dni. Postęp jest zapisywany; wznów ręcznie.',
  ],
  'tr': [
    'WARP yapılandırması oluştur',
    'Uç noktaları tara',
    'Hızlı tarama',
    'Tek IP tara',
    'Tüm IPv4 havuzu',
    'Duraklat',
    'Sürdür',
    'Ülke / bölge',
    'Tarama geçmişi',
    'Sonraki sayfa',
    'Gözlem zamanı',
    'Bilinmiyor',
    'Taranıyor',
    'Duraklatıldı',
    'Tamamlandı',
    'İptal edildi',
    'Başarısız',
    'Tüm ülkeler',
    'Dış bağlantı değişti. Yeni bir tarama başlatın.',
    'WARP hesabını ve MASQUE bağlantısını kontrol edip yeniden deneyin.',
    'Ülkeler ayrı bir tarama kimliğiyle alınan Cloudflare gözlemleridir. Bağlanırken yapılandırmanız yeniden ölçülür.',
    'Tam tarama günler sürebilir. İlerleme kaydedilir; elle sürdürebilirsiniz.',
  ],
  'id': [
    'Buat konfigurasi WARP',
    'Pindai endpoint',
    'Pindai cepat',
    'Pindai satu IP',
    'Seluruh kumpulan IPv4',
    'Jeda',
    'Lanjutkan',
    'Negara / wilayah',
    'Riwayat pemindaian',
    'Halaman berikutnya',
    'Diamati',
    'Tidak diketahui',
    'Memindai',
    'Dijeda',
    'Selesai',
    'Dibatalkan',
    'Gagal',
    'Semua negara',
    'Koneksi luar berubah. Mulai pemindaian baru.',
    'Periksa akun WARP dan koneksi MASQUE, lalu coba lagi.',
    'Negara berasal dari pengamatan Cloudflare dengan identitas pemindaian terpisah. Konfigurasi Anda diperiksa saat tersambung.',
    'Pemindaian lengkap dapat memakan waktu berhari-hari. Kemajuan disimpan; lanjutkan secara manual.',
  ],
  'vi': [
    'Tạo cấu hình WARP',
    'Quét điểm cuối',
    'Quét nhanh',
    'Quét một IP',
    'Toàn bộ nhóm IPv4',
    'Tạm dừng',
    'Tiếp tục',
    'Quốc gia / khu vực',
    'Lịch sử quét',
    'Trang tiếp',
    'Thời gian đo',
    'Không rõ',
    'Đang quét',
    'Đã tạm dừng',
    'Hoàn tất',
    'Đã hủy',
    'Thất bại',
    'Mọi quốc gia',
    'Kết nối bên ngoài đã thay đổi. Hãy bắt đầu lượt quét mới.',
    'Kiểm tra tài khoản WARP và kết nối MASQUE rồi thử lại.',
    'Quốc gia là quan sát của Cloudflare qua danh tính quét riêng. Cấu hình của bạn được đo lại khi kết nối.',
    'Quét toàn bộ có thể mất nhiều ngày. Tiến độ được lưu; bạn có thể tiếp tục thủ công.',
  ],
  'th': [
    'สร้างการตั้งค่า WARP',
    'สแกนจุดเชื่อมต่อ',
    'สแกนด่วน',
    'สแกน IP เดียว',
    'พูล IPv4 ทั้งหมด',
    'หยุดชั่วคราว',
    'ดำเนินการต่อ',
    'ประเทศ / ภูมิภาค',
    'ประวัติการสแกน',
    'หน้าถัดไป',
    'เวลาที่ตรวจสอบ',
    'ไม่ทราบ',
    'กำลังสแกน',
    'หยุดชั่วคราวแล้ว',
    'เสร็จสิ้น',
    'ยกเลิกแล้ว',
    'ล้มเหลว',
    'ทุกประเทศ',
    'การเชื่อมต่อภายนอกเปลี่ยนแล้ว โปรดเริ่มการสแกนใหม่',
    'ตรวจสอบบัญชี WARP และการเชื่อมต่อ MASQUE แล้วลองอีกครั้ง',
    'ประเทศมาจากการตรวจสอบของ Cloudflare ด้วยข้อมูลประจำตัวแยกต่างหาก ระบบจะตรวจสอบการตั้งค่าของคุณอีกครั้งเมื่อเชื่อมต่อ',
    'การสแกนทั้งหมดอาจใช้เวลาหลายวัน ระบบบันทึกความคืบหน้าให้ดำเนินการต่อด้วยตนเอง',
  ],
  'ar': [
    'إنشاء إعداد WARP',
    'فحص نقاط الاتصال',
    'فحص سريع',
    'فحص عنوان IP واحد',
    'مجموعة IPv4 كاملة',
    'إيقاف مؤقت',
    'استئناف',
    'البلد / المنطقة',
    'سجل الفحص',
    'الصفحة التالية',
    'وقت الرصد',
    'غير معروف',
    'جارٍ الفحص',
    'متوقف مؤقتًا',
    'مكتمل',
    'ملغى',
    'فشل',
    'كل البلدان',
    'تغير الاتصال الخارجي. ابدأ فحصًا جديدًا.',
    'تحقق من حساب WARP واتصال MASQUE ثم أعد المحاولة.',
    'البلدان هي نتائج رصد Cloudflare بهوية فحص منفصلة. يعاد فحص إعدادك عند الاتصال.',
    'قد يستغرق الفحص الكامل أيامًا. يحفظ التقدم ويمكن استئنافه يدويًا.',
  ],
  'fa': [
    'ساخت پیکربندی WARP',
    'پویش نقاط اتصال',
    'پویش سریع',
    'پویش یک IP',
    'تمام مخزن IPv4',
    'مکث',
    'ادامه',
    'کشور / منطقه',
    'تاریخچهٔ پویش',
    'صفحهٔ بعد',
    'زمان مشاهده',
    'نامشخص',
    'در حال پویش',
    'متوقف شده',
    'تکمیل شد',
    'لغو شد',
    'ناموفق',
    'همهٔ کشورها',
    'اتصال بیرونی تغییر کرده است. پویش تازه‌ای آغاز کنید.',
    'حساب WARP و اتصال MASQUE را بررسی و دوباره تلاش کنید.',
    'کشورها مشاهده‌های Cloudflare با هویت پویش جداگانه هستند. پیکربندی شما هنگام اتصال دوباره سنجیده می‌شود.',
    'پویش کامل ممکن است چند روز طول بکشد. پیشرفت ذخیره می‌شود؛ دستی ادامه دهید.',
  ],
};

extension WarpStrings on AppStrings {
  String warp(String key) {
    final index = _keys.indexOf(key);
    if (index < 0) return key;
    return (kWarpCatalogs[catalogId] ?? kWarpCatalogs['en']!)[index];
  }
}
